_BASE_: "faster_rcnn_R_50_FPN_sup10_run1-instagram.yaml"
SOLVER:
    BASE_LR: 0.005
    MAX_ITER: 50000
    IMG_PER_BATCH_LABEL: 8
    IMG_PER_BATCH_UNLABEL: 8
    IMS_PER_BATCH: 8
SEMISUPNET:
    BURN_UP_STEP: 500
