_BASE_: "faster_rcnn_R_50_FPN_sup10_run1-instagram.yaml"
SOLVER:
    BASE_LR: 0.005
    MAX_ITER: 100000
    IMG_PER_BATCH_LABEL: 4
    IMG_PER_BATCH_UNLABEL: 4
    IMS_PER_BATCH: 4
SEMISUPNET:
    BURN_UP_STEP: 1000

